name: publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_pub_publish.yml@v1
    with:
      pub_credentials: secrets.PUB_CREDENTIALS
